[package]
name = "oxidart"
version = "0.1.0"
edition = "2024"
description = "A very fast Tree that support get/set/del operations"
license = "MPL-2.0"

[dependencies]
arrayvec = "0.7.6"
bytes = "1.11.0"
slab = "0.4.11"
smallvec = "1.15.1"
